# Generated by Django 3.1.7 on 2021-05-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('sub_title', models.CharField(default='', max_length=255)),
                ('images', models.ManyToManyField(to='news.ImageModel')),
            ],
        ),
    ]
