# Generated by Django 3.1.7 on 2021-05-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210524_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlenews',
            name='images',
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
