# Generated by Django 3.1.7 on 2021-05-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210524_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlenews',
            name='images',
        ),
        migrations.AddField(
            model_name='articlenews',
            name='images',
            field=models.ManyToManyField(to='news.ImageModel'),
        ),
    ]
