# Generated by Django 3.1.7 on 2021-05-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210524_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlenews',
            options={'verbose_name_plural': 'บทความข่าวสาร'},
        ),
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name_plural': 'รูปที่อัพโหลด'},
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
