# Generated by Django 3.1.7 on 2021-05-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210524_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='image',
            new_name='image_url',
        ),
    ]
