# Generated by Django 3.1.7 on 2021-05-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210524_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
