# Generated by Django 3.1.7 on 2021-05-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20210524_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlenews',
            name='images',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='image_url',
        ),
        migrations.AddField(
            model_name='articlenews',
            name='gallery',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='images',
            field=models.ManyToManyField(to='news.ArticleNews'),
        ),
    ]
