# Generated by Django 3.1.7 on 2021-05-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210524_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='images',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='articlenews',
            name='gallery',
        ),
        migrations.AddField(
            model_name='articlenews',
            name='gallery',
            field=models.ManyToManyField(to='news.ImageModel'),
        ),
    ]
