# Generated by Django 3.1.7 on 2021-05-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210524_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlenews',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
