# Generated by Django 3.1.7 on 2021-05-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20210525_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlenews',
            old_name='cover',
            new_name='cover_url',
        ),
        migrations.AddField(
            model_name='articlenews',
            name='detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='articlenews',
            name='images_article',
            field=models.TextField(default='', help_text='Input your url Ex. images1.png, images2.jpg'),
        ),
    ]
