# Generated by Django 3.1.7 on 2021-05-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210525_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlenews',
            name='images_article',
        ),
        migrations.AddField(
            model_name='articlenews',
            name='images_article_url',
            field=models.TextField(default='https://firebasestorage.googleapis.com/v0/b/kms-media.appspot.com/o/placeholder-images%2F800.png?alt=media&token=0519bc05-b421-455f-b932-21a271723607', help_text='Ex.images1.png, images2.jpg'),
        ),
    ]
