# Generated by Django 3.1.7 on 2021-05-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20210525_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlenews',
            name='images_article_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
