# Generated by Django 3.1.7 on 2021-05-24 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20210525_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.articlenews')),
            ],
        ),
    ]
