# Generated by Django 3.1.7 on 2021-05-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20210525_0211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryArticle',
        ),
    ]
