# Generated by Django 3.1.7 on 2021-05-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_articlenews_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlenews',
            name='images_article_url_1',
            field=models.CharField(blank=True, default='', help_text='image url (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlenews',
            name='images_article_url_2',
            field=models.CharField(blank=True, default='', help_text='image url (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlenews',
            name='images_article_url_3',
            field=models.CharField(blank=True, default='', help_text='image url (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlenews',
            name='images_article_url_4',
            field=models.CharField(blank=True, default='', help_text='image url (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlenews',
            name='images_article_url_5',
            field=models.CharField(blank=True, default='', help_text='image url (optional)', max_length=255, null=True),
        ),
    ]
