# Generated by Django 3.1.7 on 2021-05-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_articlenews_hyper_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlenews',
            name='hyper_link',
            field=models.CharField(blank=True, help_text='add your hyper link to readmore', max_length=255, null=True),
        ),
    ]
