# Generated by Django 3.1.7 on 2021-05-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name_plural': 'ประเภทบทความ'},
        ),
        migrations.RenameField(
            model_name='documenttype',
            old_name='document_file',
            new_name='document_image',
        ),
    ]
