# Generated by Django 3.1.7 on 2021-05-23 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20210524_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.CharField(default='', max_length=255)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='document.documenttype')),
            ],
        ),
    ]
