# Generated by Django 3.1.7 on 2021-05-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_documenttemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'verbose_name_plural': 'เทมเพลตเอกสาร'},
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='document_image',
        ),
    ]
