# Generated by Django 3.1.7 on 2021-05-23 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0004_auto_20210524_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='', max_length=25)),
                ('student_code', models.CharField(default='', max_length=25)),
                ('document_file', models.CharField(default='', max_length=255)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='document.documenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ตรวจสอบ / รีวิวเอกสาร',
            },
        ),
    ]
