# Generated by Django 3.1.7 on 2021-05-23 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_documentreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentreview',
            old_name='document_file',
            new_name='document_file_review',
        ),
    ]
