# Generated by Django 3.1.7 on 2021-05-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20210524_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreview',
            name='document_status',
            field=models.CharField(default='waiting', max_length=24),
        ),
    ]
