# Generated by Django 3.1.7 on 2021-05-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_documentreview_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreview',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentreview',
            name='document_status',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('waiting', 'Waiting')], default='waiting', max_length=24),
        ),
    ]
