# Generated by Django 3.1.7 on 2021-05-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20210524_0458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name_plural': 'ประเภทเอกสาร'},
        ),
    ]
