# Generated by Django 3.1.7 on 2021-05-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_auto_20210524_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='department',
            field=models.CharField(choices=[('mdt', 'MDT'), ('mda', 'MDA'), ('mmda', 'MMDA')], default='mdt', max_length=100),
        ),
    ]
