# Generated by Django 3.1.7 on 2021-05-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_documenttemplate_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreview',
            name='department',
            field=models.CharField(choices=[('mdt', 'MDT'), ('mda', 'MDA'), ('mmda', 'MMDA')], default='mdt', max_length=100),
        ),
    ]
