# Generated by Django 3.1.7 on 2021-05-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_documentreview_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
