# Generated by Django 3.1.7 on 2021-05-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_documenttemplate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreview',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
