# Generated by Django 3.1.7 on 2021-05-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_auto_20210530_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentreview',
            name='document_template',
        ),
    ]
