# Generated by Django 3.1.7 on 2021-05-29 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_auto_20210530_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreview',
            name='template',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fk_template', to='document.documenttemplate'),
        ),
    ]
