# Generated by Django 3.1.7 on 2021-05-29 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0020_remove_documentreview_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentreview',
            name='template',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='document.documenttemplate'),
        ),
    ]
