# Generated by Django 3.1.7 on 2021-04-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
