# Generated by Django 3.1.7 on 2021-04-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210412_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='own_user',
            field=models.CharField(default='', max_length=11),
        ),
    ]
