# Generated by Django 3.1.7 on 2021-04-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210412_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
    ]
