# Generated by Django 3.1.7 on 2021-04-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_own_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='own_user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
