# Generated by Django 3.1.7 on 2021-04-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_merge_20210423_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='own_user',
        ),
        migrations.AlterField(
            model_name='blog',
            name='sub_title',
            field=models.TextField(default=''),
        ),
    ]
