# Generated by Django 3.1.7 on 2021-04-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210418_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='own_user',
            new_name='own_user_post',
        ),
    ]
