# Generated by Django 3.1.7 on 2021-04-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210418_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='own_user_post',
        ),
    ]
