# Generated by Django 3.1.7 on 2021-04-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_comment_own_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='owner_user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
