# Generated by Django 3.1.7 on 2021-04-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comment_owner_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner_user',
            new_name='owner',
        ),
    ]
