# Generated by Django 3.1.7 on 2021-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_comment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sub_title',
            field=models.TextField(default=''),
        ),
    ]
