# Generated by Django 3.1.7 on 2021-04-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_blogcategory_slug'),
        ('blog', '0018_auto_20210422_1932'),
    ]

    operations = [
    ]
