# Generated by Django 3.1.7 on 2021-05-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_articlelikeandunlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelikeandunlike',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
