# Generated by Django 3.1.7 on 2021-05-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionAnswer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiontopic',
            options={'verbose_name_plural': 'คำถามในระบบ'},
        ),
        migrations.AddField(
            model_name='questiontopic',
            name='question_detail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='questiontopic',
            name='sub_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='questiontopic',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
