# Generated by Django 3.1.7 on 2021-03-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageUser', '0002_auto_20210317_1554'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email',)},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
