# Generated by Django 3.1.7 on 2021-03-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageUser', '0003_auto_20210317_0300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
