# Generated by Django 3.1.7 on 2021-04-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageUser', '0003_auto_20210317_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'จัดการผู้ใช้งาน'},
        ),
    ]
